import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import UpperHeaader from "./components/HomePage/Header";
import HeroSection from "./components/HomePage/HeroSection";
import Brand from "./components/HomePage/Brand";
import NewArrivals from "./components/HomePage/NewArrivals";
import TopSelling from "./components/HomePage/TopSelling";
import HappyCustomers from "./components/HomePage/OurHappyCostomers";
import Footer from "./components/HomePage/Footer";
import DressStyleBrowser from "./components/HomePage/BrowseByDressStyle";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      ><UpperHeaader />
      <HeroSection />
      <Brand />
      <NewArrivals />
      <TopSelling />
      <DressStyleBrowser />
      <HappyCustomers />
      
      
      
        {children}
        <Footer />
      </body>
    </html>
  );
}
